### PR TITLE
1 new site

### PR DESCRIPTION
**Pull request by HoshyarKarimi**
added `https://downloadly.ir`

### CODE REVIEW

**Comment by amirmojiry** [comment]
I tested it, and it opened without Iran IP. I also tried downloading files. Could you please explain more about this PR?

**Comment by HoshyarKarimi** [comment]
image

**Comment by HoshyarKarimi** [comment]
> I tested it, and it opened without Iran IP. I also tried downloading files. Could you please explain more about this PR?

Maybe their GeoIP database is not up to date, but the error message is obviously saying they are using GeoIP restrictions.

**Comment by xhdix** [comment]
This is not related, but I received this screenshot from a user two days ago:

image

**Pull request merged**
